---
- name: Pull Docker image
  docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Create containers
  docker_container:
    name: "{{ default_container_name }}"
    image: "{{ default_container_image }}"
    #    command: "{{ default_container_command }}"
    state: started
    published_ports:
      - "{{ ports }}"
##    with_sequence: count={{ container_count }}  
